plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json

author: Jing Tian Feng
title: Jekytrap
tagline: SSG made simple
description: Template for Jekyll + Bootstrap 5
url: https://jingtianfeng.github.io/jekytrap
logo: /assets/img/logo.png
