plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json

author: Jing Tian Feng
title: JT Feng
tagline: My life demystified
description: Welcome to my personal corner of the internet!
url: https://jtfeng.com
logo: /assets/img/logo.png
